from setuptools import find_packages, setup

setup(
    name="kdags",
    packages=find_packages(exclude=["kdags_tests"]),
    install_requires=[
        "dagster",
        "dagster-webserver",
        "pandas",
        "polars",
        "matplotlib",
        "msal",
        "Office365-REST-Python-Client",
        "openpyxl",
        "firebase-admin",
        "azure-storage-blob",
        "azure-storage-file-datalake",
        "rapidfuzz",
        "xlsxwriter",
        "xlrd",
        "pdfplumber",
        "pypxlib",
        "pyarrow",
        "selenium",
        "lxml",
        "fastexcel",
        "xlsx2csv",
        "black",
        "adlfs",
        "plotnine",
        "scipy",
        "azure-storage-file-share",
    ],
    extras_require={"dev": ["dagster-webserver", "pytest"]},
)
