"W11120007":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14030010T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W13050087":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14100053T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W09030007":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W12010004":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W12010012":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX15040005T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX1902Y002T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14010001T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX1712Y002T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W11120008":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX1505Y006":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14020007T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W13060060":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W13040080":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14080032T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14100050T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX1902Y001T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W12030041":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14100055T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W11120011":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14020005T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14030012T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX141000517":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W12010002":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W11100008":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14030014T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX1609Y005T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX1505Y007":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W12020025":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14100044T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX1612Y006T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W11110017":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W11110015":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX15030002T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14020004T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W11120018":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14020006T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WU12010014":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W11110001":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W08090001":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14100047T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14110056T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14090043T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14100052T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W11120019":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14080033T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14060028T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W08100003":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W12010001":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14090039T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14020003T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W11110006":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX12010013":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W12010016":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX1612Y007T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W08080004":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W12010015":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14090036T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX2212Y004T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX15020001T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14020009T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14110058T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W05100001":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W11110013":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W11110014":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX1410049T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14060027T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W08100002":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W12010009A":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14080030T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W08040005":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W12030036":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14110057T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX15030003T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14120060T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W13020043":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W11120020":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14100054T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W13030037":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W12010005":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W12010011":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX1701Y00IT":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14110059T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14100045T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W12010003":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W13070053":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14090042T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W12010017":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"W11110005":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14100048T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
"WX14080031T":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
#- component_serial: W05100007
#  subcomponent_name: transmision
#  retired_date: '2020-11-17'
#  last_service_order: 14111275
#  is_retired: true
#- component_serial: WX14100051T
#  subcomponent_name: transmision
#  retired_date: '2019-10-19'
#  last_service_order: 14105367
#  is_retired: true
#- component_serial: WX14020008T
#  subcomponent_name: transmision
#  retired_date: '2025-01-10'
#  last_service_order: 14144670
#  is_retired: true
#- component_serial: WX14040016T
#  subcomponent_name: transmision
#  retired_date: "2021-11-10"
#  last_service_order: 14120389 #09-07-2021
#  is_retired: True
#- component_serial: W11120009
#  subcomponent_name: transmision
#  retired_date: '2025-03-04'
#  last_service_order: 14124578
#  is_retired: true
#- component_serial: W13040074
#  subcomponent_name: transmision
#  retired_date: '2023-06-28'
#  last_service_order: 14131730
#  is_retired: true
#- component_serial: WX14100046T
#  subcomponent_name: transmision
#  retired_date: null
#  last_service_order: -1
#  is_retired: False
#- component_serial: WX1606Y004T
#  subcomponent_name: transmision
#  last_changeout_date: null
#  last_service_order: -1
#  is_retired: False