"W11120007":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14150557
  retrofit_date: 03-12-2024
"WX14030010T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14144531
  retrofit_date: 24-04-2024
"W13050087":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14145733
"WX14100053T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14141487
"W09030007":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14131459
"W12010004":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14132475
"W12010012":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14118196
"WX15040005T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14138357
"WX1902Y002T":
  subcomponent_tag: 0980
  retired: false
"WX14010001T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14122438
"WX1712Y002T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14144881
"W11120008":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 13011820
"WX1505Y006":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14114778
"WX14020007T":
  subcomponent_tag: 0980
  retired: false
"W13060060":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14125908
"W13040080":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14115796
"WX14080032T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14143311
"WX14100050T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14120158
"WX1902Y001T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14134488
"W12030041":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14146524
"WX14100055T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14128349
"W11120011":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14129197
"WX14020005T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14124335
"WX14030012T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14144433
"WX141000517":
  subcomponent_tag: 0980
  retired: false
  retired_date: null
  retrofit_service_order: 14120279
"W12010002":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14120872
"W11100008":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14136826
"WX14030014T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14113885
"WX1609Y005T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14144237
"WX1505Y007":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14119151
"W12020025":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14138933
"WX14100044T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14137476
"WX1612Y006T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14121965
"W11110017":
  subcomponent_tag: 0980
  retired: false
"W11110015":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14147441
"WX14080031T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14130971
"WX14020004T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14136698
"W11120018":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14136556
"WX14020006T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14130419
"WU12010014":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14123904
"W11110001":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 13011481
"W08090001":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14135144
"WX14100047T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14115972
"WX14110056T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14122284
"WX14090043T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14121841
"WX14100052T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14141226
"W11120019":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14118998
"WX14080033T":
  subcomponent_tag: 0980
  retired: false
"WX14060028T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14133929
"W08100003":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14129594
"W12010001":
  subcomponent_tag: 0980
  retired: false
"WX14090039T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14120985
"WX14020003T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14125119
"W11110006":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 13011625
"WX12010013":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14115749
"W12010016":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14139738
"WX1612Y007T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14130234
"W08080004":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14117499
"W12010015":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14120705
"WX14090036T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14134954
"WX2212Y004T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14144238
"WX15020001T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14115748
"WX14020009T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14127855
"WX14110058T":
  subcomponent_tag: 0980
  retired: false
"W05100001":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14136015
"W11110013":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14144680
"W11110014":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14136202
"WX1410049T":
  subcomponent_tag: 0980
  retired: false
"WX14060027T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14112907
"W08100002":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 13010801
"W12010009A":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14138043
"WX14080030T":
  subcomponent_tag: 0980
  retired: false
"W08040005":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14146392
"W12030036":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14141373
"WX14110057T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14115014
"WX15030003T":
  subcomponent_tag: 0980
  retired: false
"WX14120060T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14120330
"W13020043":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14130552
"W11120020":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14128790
"WX14100054T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14133417
"W13030037":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14121043
"W12010005":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14124091
"W12010011":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14138315
"WX1701Y00IT":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14130682
"WX15030002T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14118359
"WX14110059T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14113611
"WX14100045T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 13011261
"W12010003":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14115747
"W13070053":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14133954
"WX14090042T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14130260
"W12010017":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14113260
"W11110005":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14111500
"WX14100048T":
  subcomponent_tag: 0980
  retired: false
  retrofit_service_order: 14122848
#- component_serial: W05100007
#  subcomponent_name: transmision
#  retired_date: '2020-11-17'
#  last_service_order: 14111275
#  is_retired: true
#- component_serial: WX14100051T
#  subcomponent_name: transmision
#  retired_date: '2019-10-19'
#  last_service_order: 14105367
#  is_retired: true
#- component_serial: WX14020008T
#  subcomponent_name: transmision
#  retired_date: '2025-01-10'
#  last_service_order: 14144670
#  is_retired: true
#- component_serial: WX14040016T
#  subcomponent_name: transmision
#  retired_date: "2021-11-10"
#  last_service_order: 14120389 #09-07-2021
#  is_retired: True
#- component_serial: W11120009
#  subcomponent_name: transmision
#  retired_date: '2025-03-04'
#  last_service_order: 14124578
#  is_retired: true
#- component_serial: W13040074
#  subcomponent_name: transmision
#  retired_date: '2023-06-28'
#  last_service_order: 14131730
#  is_retired: true
#- component_serial: WX14100046T
#  subcomponent_name: transmision
#  retired_date: null
#  last_service_order: -1
#  is_retired: False
#- component_serial: WX1606Y004T
#  subcomponent_name: transmision
#  last_changeout_date: null
#  last_service_order: -1
#  is_retired: False