planning:
  component_changeouts:
    raw_path: ...
    analytics_path: az://bhp-analytics-data/PLANNING/COMPONENT_CHANGEOUTS/component_changeouts.parquet
    description: ...
    source: ...
    responsible: asdasd
  component_reparations:
    analytics_path: az://bhp-analytics-data/PLANNING/COMPONENT_REPARATIONS/component_reparations.parquet
maintenance:
  oil_analysis:
    raw_path: az://bhp-raw-data/LUBE_ANALYST/SCAAE
    analytics_path: az://bhp-analytics-data/MAINTENANCE/OIL_ANALYSIS/oil_analysis.parquet
    publish_path:
      - sp://KCHCLSP00022/01.%20%C3%81REAS%20KCH/1.6%20CONFIABILIDAD/JEFE_CONFIABILIDAD/MANTENIMIENTO/analisis_aceite.xlsx
      - sp://KCHCLGR00058/___/MANTENIMIENTO/analisis_aceite.xlsx
    description: ...
    source: sad
    responsible: .asd
reparation:
  so_report:
    analytics_path: az://bhp-analytics-data/REPARATION/SERVICE_ORDER_REPORT/service_order_report.parquet
  so_quotations:
    raw_path: az://bhp-raw-data/RESO/SERVICE_ORDER_DETAILS/so_quotations.parquet
    analytics_path: az://bhp-analytics-data/RELIABILITY/QUOTATIONS/quotations.parquet
  so_documents:
    raw_path: az://bhp-raw-data/RESO/SERVICE_ORDER_DETAILS/so_documents.parquet
reference:
  pcp_repair_costs:
    raw_path: az://bhp-raw-data/REFERENCE/pcp_repair_costs.xlsx
  gfa_overhaul_rates:
    raw_path: az://bhp-raw-data/REFERENCE/gfa_overhaul_rates.xlsx
reliability:
  # INPUTS REFERENCIA
  warranties:
    reference_path: sp://KCHCLSP00022/01.%20%C3%81REAS%20KCH/1.6%20CONFIABILIDAD/JEFE_CONFIABILIDAD/REFERENCE/warranties.xlsx
    analytics_path: az://bhp-analytics-data/RELIABILITY/WARRANTIES/warranties.parquet
  monitored_conditions:
    reference_path: sp://KCHCLSP00022/01.%20%C3%81REAS%20KCH/1.6%20CONFIABILIDAD/JEFE_CONFIABILIDAD/REFERENCE/monitored_conditions.xlsx
  non_conformities:
    reference_path: sp://KCHCLSP00022/01.%20%C3%81REAS%20KCH/1.6%20CONFIABILIDAD/JEFE_CONFIABILIDAD/REFERENCE/non_conformities.xlsx
  psg_requests:
    reference_path: sp://KCHCLSP00022/01.%20%C3%81REAS%20KCH/1.6%20CONFIABILIDAD/JEFE_CONFIABILIDAD/REFERENCE/psg_requests.xlsx
  ep:
    reference_path: sp://KCHCLSP00022/01.%20%C3%81REAS%20KCH/1.6%20CONFIABILIDAD/JEFE_CONFIABILIDAD/REFERENCE/ep.xlsx
    analytics_path: az://bhp-analytics-data/RELIABILITY/EP/ep.parquet
  component_lifeline:
    analytics_path: az://bhp-analytics-data/RELIABILITY/COMPONENT_LIFELINE/component_lifeline.parquet
  component_snapshots:
    analytics_path: az://bhp-analytics-data/RELIABILITY/COMPONENT_SNAPSHOTS/component_snapshots.parquet
  component_states:
    analytics_path: az://bhp-analytics-data/RELIABILITY/COMPONENT_STATES/component_states.parquet
  icc:
    analytics_path: az://bhp-analytics-data/RELIABILITY/ICC/icc.parquet

