docs:
  publish_catalog:
    publish_path: "sp://KCHCLGR00058/___/Catálogo Datos.xlsx"
operation:
  komtrax_smr:
    process_path: az://bhp-process-data/KOMTRAX/smr.parquet
    analytics_path: az://bhp-process-data/OPERATION/smr.parquet
components:
  component_changeouts:
    reference_path:
      spence: sp://KCHCLSP00060/1.- Gestión de Componentes/2.- Spence/1.- Planilla Control cambio de componentes/Planilla control cambio componentes/NUEVA PLANILLA DE CONTROL CAMBIO DE COMPONENTES SPENCE.xlsx
      mel: sp://KCHCLSP00022/01. ÁREAS KCH/1.3 PLANIFICACION/01. Gestión pool de componentes/01. Control Cambio Componentes/PLANILLA DE CONTROL CAMBIO DE COMPONENTES.xlsx
    analytics_path: az://bhp-analytics-data/COMPONENTS/COMPONENT_CHANGEOUTS/component_changeouts.parquet
  patched_component_changeouts:
    reference_path: sp://KCHCLSP00022/01. ÁREAS KCH/1.6 CONFIABILIDAD/JEFE_CONFIABILIDAD/REFERENCE/patched_component_changeouts.xlsx
  component_history:
    analytics_path: az://bhp-analytics-data/COMPONENTS/COMPONENT_HISTORY/component_history.parquet
    publish_path: "sp://KCHCLGR00058/___/COMPONENTES/Historial Componentes.xlsx"
  component_reparations:
    analytics_path: az://bhp-analytics-data/COMPONENTS/COMPONENT_REPARATIONS/component_reparations.parquet
    publish_path: "sp://KCHCLGR00058/___/REPARACION/Reparación Componentes.xlsx"
maintenance:
  oil_analysis:
    raw_path: az://bhp-raw-data/LUBE_ANALYST/SCAAE
    analytics_path: az://bhp-analytics-data/MAINTENANCE/OIL_ANALYSIS/oil_analysis.parquet
    publish_path: "sp://KCHCLGR00058/___/MANTENIMIENTO/Historial Muestras Aceite.xlsx"
  work_schedule:
    raw_path: az://bhp-raw-data/FIORI/WORK_SCHEDULE
  work_order_history:
    raw_path: az://bhp-raw-data/FIORI/WORK_ORDER_HISTORY
    manifest_path: az://bhp-process-data/STATE/FIORI/WORK_ORDER_HISTORY/manifest.parquet
    analytics_path: az://bhp-analytics-data/MAINTENANCE/WORK_ORDER_HISTORY/work_order_history.parquet
    publish_path: "sp://KCHCLGR00058/___/MANTENIMIENTO/Historial Órdenes Trabajo.xlsx"
reparation:
  so_report:
    analytics_path: az://bhp-analytics-data/REPARATION/SERVICE_ORDER_REPORT/service_order_report.parquet
  so_quotations:
    raw_path: az://bhp-raw-data/RESO/SERVICE_ORDER_DETAILS/so_quotations.parquet
    analytics_path: az://bhp-analytics-data/REPARATION/QUOTATIONS/quotations.parquet
  so_documents:
    raw_path: az://bhp-raw-data/RESO/SERVICE_ORDER_DETAILS/so_documents.parquet
    analytics_path: az://bhp-analytics-data/REPARATION/so_documents.parquet
  quotations:
    analytics_path: az://bhp-analytics-data/REPARATION/quotations.parquet
    publish_path: "sp://KCHCLGR00058/___/REPARACION/Presupuestos.xlsx"
  sd_docs:
    analytics_path: az://bhp-process-data/RESO/DOCUMENTS/sd.parquet
  mt_docs:
    analytics_path: az://bhp-process-data/RESO/DOCUMENTS/mt.parquet
reference:
  pcp_repair_costs:
    raw_path: az://bhp-raw-data/REFERENCE/pcp_repair_costs.xlsx
  gfa_overhaul_rates:
    raw_path: az://bhp-raw-data/REFERENCE/gfa_overhaul_rates.xlsx
reliability:
  component_fleet:
    analytics_path: az://bhp-analytics-data/RELIABILITY/component_fleet.parquet
    publish_path: "sp://KCHCLSP00022/01. ÁREAS KCH/1.6 CONFIABILIDAD/JEFE_CONFIABILIDAD/FlottenMeister.xlsx"
  # INPUTS REFERENCIA
  warranties:
    reference_path: sp://KCHCLSP00022/01. ÁREAS KCH/1.6 CONFIABILIDAD/JEFE_CONFIABILIDAD/REFERENCE/warranties.xlsx
    analytics_path: az://bhp-analytics-data/RELIABILITY/WARRANTIES/warranties.parquet
  monitored_conditions:
    reference_path: sp://KCHCLSP00022/01. ÁREAS KCH/1.6 CONFIABILIDAD/JEFE_CONFIABILIDAD/REFERENCE/monitored_conditions.xlsx
  non_conformities:
    reference_path: sp://KCHCLSP00022/01. ÁREAS KCH/1.6 CONFIABILIDAD/JEFE_CONFIABILIDAD/REFERENCE/non_conformities.xlsx
  psg_requests:
    reference_path: sp://KCHCLSP00022/01. ÁREAS KCH/1.6 CONFIABILIDAD/JEFE_CONFIABILIDAD/REFERENCE/psg_requests.xlsx
  ep:
    reference_path: sp://KCHCLSP00022/01. ÁREAS KCH/1.6 CONFIABILIDAD/CAEX/ANTECEDENTES/Análisis Cambios Componentes.xlsx
    analytics_path: az://bhp-analytics-data/RELIABILITY/EP/ep.parquet
    publish_path: "sp://KCHCLGR00058/___/CONFIABILIDAD/Estado Pago.xlsx"
  tidy_ep:
    publish_path: "sp://KCHCLGR00058/___/CONFIABILIDAD/Tidy Estado Pago.xlsx"
  component_snapshots:
    analytics_path: az://bhp-analytics-data/RELIABILITY/COMPONENT_SNAPSHOTS/component_snapshots.parquet
  component_states:
    analytics_path: az://bhp-analytics-data/RELIABILITY/COMPONENT_STATES/component_states.parquet
  icc:
    analytics_path: az://bhp-analytics-data/RELIABILITY/ICC/icc.parquet
    publish_path: "sp://KCHCLGR00058/___/CONFIABILIDAD/Informes Cambios Componentes.xlsx"

