SV082:
  equipment_model: "PC8000-6"
  equipment_serial: "12098"
TK284:
  equipment_model: "930E-4"
  equipment_serial: "A30516"
TK285:
  equipment_model: "930E-4"
  equipment_serial: "A30517"
TK286:
  equipment_model: "930E-4"
  equipment_serial: "A30528"
TK289:
  equipment_model: "930E-4"
  equipment_serial: "A30529"
TK291:
  equipment_model: "930E-4"
  equipment_serial: "A30675"
TK292:
  equipment_model: "930E-4"
  equipment_serial: "A30676"
TK320:
  equipment_model: "960E"
  equipment_serial: "A30003"
TK322:
  equipment_model: "960E"
  equipment_serial: "A30006"
TK396:
  equipment_model: "960E"
  equipment_serial: "A30039"
TK397:
  equipment_model: "960E"
  equipment_serial: "A30040"
TK398:
  equipment_model: "960E"
  equipment_serial: "A30041"
TK399:
  equipment_model: "960E"
  equipment_serial: "A30042"
TK847:
  equipment_model: "960E"
  equipment_serial: "A30044"
TK848:
  equipment_model: "960E"
  equipment_serial: "A30045"
TK849:
  equipment_model: "960E"
  equipment_serial: "A30046"
TK850:
  equipment_model: "960E"
  equipment_serial: "A30048"
TK851:
  equipment_model: "960E"
  equipment_serial: "A30049"
TK852:
  equipment_model: "960E"
  equipment_serial: "A30050"
TK853:
  equipment_model: "960E"
  equipment_serial: "A30051"
TK854:
  equipment_model: "960E"
  equipment_serial: "A30052"
TK855:
  equipment_model: "960E"
  equipment_serial: "A30053"
TK856:
  equipment_model: "960E"
  equipment_serial: "A30054"
TK857:
  equipment_model: "960E"
  equipment_serial: "A30055"
TK858:
  equipment_model: "960E"
  equipment_serial: "A30058"
TK859:
  equipment_model: "960E"
  equipment_serial: "A30074"
TK860:
  equipment_model: "960E"
  equipment_serial: "A30075"
TK861:
  equipment_model: "960E"
  equipment_serial: "A30076"
TK862:
  equipment_model: "960E"
  equipment_serial: "A30077"
TK863:
  equipment_model: "960E"
  equipment_serial: "A30078"
TK864:
  equipment_model: "960E"
  equipment_serial: "A30079"
TK865:
  equipment_model: "960E"
  equipment_serial: "A30080"
TK866:
  equipment_model: "960E"
  equipment_serial: "A30081"
TK867:
  equipment_model: "960E"
  equipment_serial: "A30082"
TK868:
  equipment_model: "960E"
  equipment_serial: "A30083"
TK869:
  equipment_model: "960E"
  equipment_serial: "A30089"
TK870:
  equipment_model: "960E"
  equipment_serial: "A30090"
TK871:
  equipment_model: "960E"
  equipment_serial: "A30091"
TK872:
  equipment_model: "960E"
  equipment_serial: "A30093"
TK873:
  equipment_model: "960E"
  equipment_serial: "A30094"
TK874:
  equipment_model: "960E"
  equipment_serial: "A30095"
TK875:
  equipment_model: "960E"
  equipment_serial: "A30098"
TK876:
  equipment_model: "960E"
  equipment_serial: "A30099"
TK877:
  equipment_model: "960E"
  equipment_serial: "A30100"
TK878:
  equipment_model: "960E"
  equipment_serial: "A30101"
TK879:
  equipment_model: "960E"
  equipment_serial: "A30102"
TK880:
  equipment_model: "960E"
  equipment_serial: "A30103"
TK881:
  equipment_model: "960E"
  equipment_serial: "A30104"
TK882:
  equipment_model: "960E"
  equipment_serial: "A30105"
TK883:
  equipment_model: "960E"
  equipment_serial: "A30106"