- component_serial: W05100007
  subcomponent_name: transmision
  last_changeout_date: '2024-03-27'
  last_service_order: 14111275
  is_retired: true
- component_serial: WX14100051T
  subcomponent_name: transmision
  last_changeout_date: '2020-08-29'
  last_service_order: 14105367
  is_retired: true
- component_serial: WX14020008T
  subcomponent_name: transmision
  last_changeout_date: '2024-03-27'
  last_service_order: 14144670
  is_retired: true
- component_serial: WX14040016T
  subcomponent_name: transmision
  last_changeout_date: null
  last_service_order: 14120389 #09-07-2021
  is_retired: True
- component_serial: W11120009
  subcomponent_name: transmision
  last_changeout_date: '2022-01-07'
  last_service_order: 14124578
  is_retired: true
- component_serial: W13040074
  subcomponent_name: transmision
  last_changeout_date: '2022-09-28'
  last_service_order: 14131730
  is_retired: true
- component_serial: WX14100046T
  subcomponent_name: transmision
  last_changeout_date: null
  last_service_order: -1
  is_retired: False
#- component_serial: WX1606Y004T
#  subcomponent_name: transmision
#  last_changeout_date: null
#  last_service_order: -1
#  is_retired: False