- component_serial: W05100007
  subcomponent_name: transmision
  retired_date: '2020-11-17'
  last_service_order: 14111275
  is_retired: true
- component_serial: WX14100051T
  subcomponent_name: transmision
  retired_date: '2019-10-19'
  last_service_order: 14105367
  is_retired: true
- component_serial: WX14020008T
  subcomponent_name: transmision
  retired_date: '2025-01-10'
  last_service_order: 14144670
  is_retired: true
- component_serial: WX14040016T
  subcomponent_name: transmision
  retired_date: "2021-11-10"
  last_service_order: 14120389 #09-07-2021
  is_retired: True
- component_serial: W11120009
  subcomponent_name: transmision
  retired_date: '2025-03-04'
  last_service_order: 14124578
  is_retired: true
- component_serial: W13040074
  subcomponent_name: transmision
  retired_date: '2023-06-28'
  last_service_order: 14131730
  is_retired: true
- component_serial: WX14100046T
  subcomponent_name: transmision
  retired_date: null
  last_service_order: -1
  is_retired: False
#- component_serial: WX1606Y004T
#  subcomponent_name: transmision
#  last_changeout_date: null
#  last_service_order: -1
#  is_retired: False