TIDY_TIBBLE_NAMES = {
    "component_name": "Componente",
    "subcomponent_name": "Subcomponente",
    "equipment_name": "Equipo",
    "position_name": "Posición",
    # "changeout_week": "Semana CC",
    # "changeout_year": "Año CC",
    # "plan_changeout_date": "Fecha Plan CC",
    # "changeout_month": "Mes Plan CC",
    # "status",
    "site_name": "Faena",
    "equipment_model": "Modelo",
    # "last_smr_date": "Última Fecha SMR",
    # "last_smr": "Último SMR",
    "changeout_date": "Fecha CC",
    "equipment_hours": "SMR",
    "component_hours": "Horas CC",
    # "last_changeout_date",
    # "last_changeout_smr",
    "mean_daily_operated_hours": "Horas Operadas Promedio",
    # "plan_operated_smr",
    # "plan_smr",
    # "component_reparation_status",
    # "plan_component_hours",
}
