- component_name: motor_traccion
  component_code: MT
  position_name:
    - derecho
    - izquierdo
  subcomponent:
    - name: transmision # Si
      code: TRANS
      main: True
#      reso:
    - name: motor_electrico # No
      code: ME
    - name: freno_servicio_trasero
    - name: freno_estacionamiento
- component_name: modulo_potencia
  component_code: MP
  position_name:
    - unico
  subcomponent:
    - name: motor
      main: True
    - name: alternador_principal # No
      code: AP
    - name: subframe
    - name: radiador
- component_name: cilindro_direccion # Si
  component_code: CD
  position_name:
    - derecho
    - izquierdo
  subcomponent:
    - name: cilindro_direccion
      code: CD
      main: True
- component_name: blower_parrilla #No
  component_code: BP
  position_name:
    - derecho
    - izquierdo
- component_name: conjunto_masa_suspension
  component_code: CMS
  position_name:
    - derecho
    - izquierdo
  subcomponent:
    - name: suspension_delantera   # Si
      reso:
        - FRONT SUSPENSION
        - asd
    - name: masa
    - name: freno_servicio_delantero
      reso:
        - FRONT SUSPENSION
- component_name: cilindro_levante  # Si
  component_code: CL
  position_name:
    - derecho
    - izquierdo
  subcomponent:
    - name: cilindro_levante
      code: CL
      main: True
      reso:
        - HOIST CYLINDER
- component_name: suspension_trasera # Si
  component_code: ST
  position_name:
    - derecho
    - izquierdo
  subcomponent:
    - name: suspension_trasera
      code: ST
      main: True
      reso:
        - REAR SUSPENSION