- component_name: motor_traccion
  component_code: MT
  position_name:
    - derecho
    - izquierdo
  warranty_hours: 3000
#  960E_unique: True
  subcomponent:
    - name: transmision
      code: TRANS
      main: True
      ep: True
    - name: motor_electrico
      code: ME
      ep: True
    - name: freno_servicio_trasero
      ep: False
    - name: freno_estacionamiento
      ep: False
- component_name: modulo_potencia
  component_code: MP
  position_name:
    - unico
  warranty_hours: 3000
  subcomponent:
    - name: alternador_principal
      code: AP
      main: True
      ep: True
    - name: motor
      ep: False
    - name: subframe
      ep: False
    - name: radiador
      ep: False
- component_name: cilindro_direccion
  component_code: CD
  position_name:
    - derecho
    - izquierdo
#  960E_unique: True
  warranty_hours: 1000
  subcomponent:
    - name: cilindro_direccion
      code: CD
      main: True
      ep: True
- component_name: blower_parrilla
  component_code: BP
  position_name:
    - derecho
    - izquierdo
  warranty_hours: 3000
  subcomponent:
    - name: blower_parrilla
      code: BP
      main: True
      ep: True
- component_name: conjunto_maza_suspension
  component_code: CMS
  position_name:
    - derecho
    - izquierdo
  warranty_hours: 1000
#  960E_unique: True
  subcomponent:
    - name: suspension_delantera
      code: SD
      main: True
      ep: True
    - name: maza
      ep: False
    - name: freno_servicio_delantero
      ep: False
- component_name: cilindro_levante
  component_code: CL
  position_name:
    - derecho
    - izquierdo
  warranty_hours: 1000
#  960E_unique: True
  subcomponent:
    - name: cilindro_levante
      code: CL
      main: True
      ep: True
- component_name: suspension_trasera
  component_code: ST
  position_name:
    - derecho
    - izquierdo
  warranty_hours: 1000
#  960E_unique: True
  subcomponent:
    - name: suspension_trasera
      code: ST
      main: True
      ep: True