OPERATION:
  effective_grade:
    source: GE
    description: "Effective grade measurements."
    data_format: dataframe
    job_name: "effective_grade_job"
    schedule: "0 5 * * *"
    input:
      storage: datalake
      path: "bhp-raw-data/GE/EFFECTIVE_GRADE/y={YYYY}/m={MM}/d={DD}"
    output:
      storage: datalake
      path: "bhp-analytics-data/GE/EFFECTIVE_GRADE/y={YYYY}/m={MM}/d={DD}"
