#OPERATION:
#  effective_grade:
#    source: GE
#    description: "Effective grade measurements."
#    data_format: dataframe
#    job_name: "effective_grade_job"
#    schedule: "0 5 * * *"
#    input:
#      storage: datalake
#      path: "bhp-raw-data/GE/EFFECTIVE_GRADE/y={YYYY}/m={MM}/d={DD}"
#    output:
#      storage: datalake
#      path: "bhp-analytics-data/GE/EFFECTIVE_GRADE/y={YYYY}/m={MM}/d={DD}"
# === PLANNING ===
PLANNING:
  component_changeouts_job:
    source: MANUAL
    description: Consolidación planilla cambio de componentes
    cron_schedule: "0 3,15 * * *"
    schedule_status: RUNNING
    input:
      path:
        - sp://KCHCLSP00022/01. ÁREAS KCH/1.3 PLANIFICACION/01. Gestión pool de componentes/01. Control Cambio Componentes/PLANILLA DE CONTROL CAMBIO DE COMPONENTES.xlsx
#        - "sp://KCHCLSP00060/1.- Gestión de Componentes/2.- Spence/1.- Planilla Control cambio de componentes/Planilla control cambio componentes/NUEVA PLANILLA DE CONTROL CAMBIO DE COMPONENTES SPENCE.xlsx"
    output:
      path: sp://KCHCLSP00022/PLANIFICACION/cambios_componentes.xlsx
MAINTENANCE:
  oil_analysis_job:
    source: SCAAE
    description: Aceites MT
    cron_schedule: "15 11 * * *"
    schedule_status: RUNNING
    input:
      path: az://bhp-raw-data/LUBE_ANALYST/SCAAE/y={YYYY}/m={MM}/d={DD}/{YYYYMMDD}SCAAE.xls
    output:
      path: az://bhp-analytics-data/MAINTENANCE/OIL_ANALYSIS/oil_analysis.parquet
    publish:
      path: sp://KCHCLSP00022/MAINTENANCE/analisis_aceite.xlsx
REPARATION:
  scrape_component_status_job:
    source: RESO
    description: Descarga Mega Estatus desde RESO
    cron_schedule: "0 9 * * FRI"
    schedule_status: RUNNING
    input:
      path: https://resoplus.komatsu.cl/WF/Reportabilidad/EstatusComponente.aspx
    output:
      path: az://bhp-raw-data/COMPONENT_STATUS/y={YYYY}/m={MM}/d={DD}
  component_status_job:
    source: RESO
    description: Consolida el mega estatus componentes RESO
    cron_schedule: "0 10 * * FRI"
    schedule_status: RUNNING
    input:
      path: az://bhp-raw-data/COMPONENT_STATUS/y={YYYY}/m={MM}/d={DD}
    output:
      path: az://bhp-analytics-data/REPARATION/COMPONENT_STATUS/component_status.parquet
    publish:
      path: sp://KCHCLSP00022/REPARACION/mega_estatus_componentes.xlsx
RELIABILITY:
  icc_job:
    source: MANUAL
    description: Verifica la existencia de los informes de cambios de componentes
    cron_schedule: "0 21 * * *"
    schedule_status: RUNNING
    input:
      path: sp://KCHCLSP00022/01. ÁREAS KCH/1.6 CONFIABILIDAD/CAEX/ANTECEDENTES/INFORMES_CAMBIO_COMPONENTES
    output:
      path: az://bhp-analytics-data/RELIABILITY/ICC/icc.parquet
    publish:
      path: sp://KCHCLSP00022/CONFIABILIDAD/informes_cambio_componentes.xlsx
